//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.21 at 02:41:30 PM GMT-03:00 
//


package ptc;


/**
 * Java content class for KeyInfoType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/xmldsig-core-schema_v1.00.xsd line 77)
 * <p>
 * <pre>
 * &lt;complexType name="KeyInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="X509Data" type="{http://www.w3.org/2000/09/xmldsig#}X509DataType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface KeyInfoType {


    /**
     * Gets the value of the x509Data property.
     * 
     * @return
     *     possible object is
     *     {@link ptc.X509DataType}
     */
    ptc.X509DataType getX509Data();

    /**
     * Sets the value of the x509Data property.
     * 
     * @param value
     *     allowed object is
     *     {@link ptc.X509DataType}
     */
    void setX509Data(ptc.X509DataType value);

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

}
