/**
 * Generated by Stylus Studio. 
 * This application skeleton demonstrates how to use Marshaller and Unmarshaller classes. 
 */

package ptc;

import java.io.FileInputStream;
import java.io.IOException;
import java.math.BigDecimal;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import java.util.List;

 
public class Main {

	/**
	 * This sample application demonstrates how to modify a collection
	 * in a Java content tree and marshall it back to XML data
	 */

	public static void main( String[] args ) {
		try {

			if( args.length != 1 ){
				System.out.println("Usage:java Main xmlfilename");
				return;
			}

			// Create a JAXBContext capable of handling classes generated into
			// the example package

			JAXBContext jc = JAXBContext.newInstance( "ptc" );

			// Create an Unmarshaller

			Unmarshaller u = jc.createUnmarshaller(); 

			// Unmarshall an XML document into a tree of Java objects.
			// Replace FooBar with your own type. 

			/**
			 *FooBar fb = (FooBar)u.unmarshal( new FileInputStream( args[0] ) ); 
			 */

			// The following code creates the Marshaller.

			Marshaller m = jc.createMarshaller();
			m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE );
			//m.marshal( fb, System.out );

		} catch( JAXBException je ) {
			je.printStackTrace();
		} 
	}
}
