//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.21 at 02:41:30 PM GMT-03:00 
//


package ptc;


/**
 * Protocolo de Transporte de Carga (PTC) do sistema de Compartilhamento Lógico de informações de trânsito de mercadorias
 * Java content class for PTC element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/ptc.xsd line 4)
 * <p>
 * <pre>
 * &lt;element name="PTC" type="{http://www.portalfiscal.inf.br/ptc}TPTC"/>
 * </pre>
 * 
 */
public interface PTC
    extends javax.xml.bind.Element, ptc.TPTC
{


}
