//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.21 at 02:41:30 PM GMT-03:00 
//


package ptc;


/**
 * Java content class for Signature element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/xmldsig-core-schema_v1.00.xsd line 20)
 * <p>
 * <pre>
 * &lt;element name="Signature" type="{http://www.w3.org/2000/09/xmldsig#}SignatureType"/>
 * </pre>
 * 
 */
public interface Signature
    extends javax.xml.bind.Element, ptc.SignatureType
{


}
