//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.21 at 02:41:30 PM GMT-03:00 
//


package ptc;


/**
 * Tipo Dados da Nota Fiscal Eletrônica
 * Java content class for TNFe complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 5)
 * <p>
 * <pre>
 * &lt;complexType name="TNFe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infNFe">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ide">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cUF" type="{http://www.portalfiscal.inf.br/nfe}TCodUfIBGE"/>
 *                             &lt;element name="nNF" type="{http://www.portalfiscal.inf.br/nfe}TNF"/>
 *                             &lt;element name="dEmi" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="emit">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice>
 *                               &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
 *                               &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
 *                             &lt;/choice>
 *                             &lt;element name="xNome">
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;maxLength value="60"/>
 *                                 &lt;minLength value="1"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/element>
 *                             &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="dest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice>
 *                               &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
 *                               &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
 *                             &lt;/choice>
 *                             &lt;element name="xNome">
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;maxLength value="60"/>
 *                                 &lt;minLength value="1"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/element>
 *                             &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="total">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ICMSTot">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="vBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
 *                                       &lt;element name="vICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
 *                                       &lt;element name="vBCST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
 *                                       &lt;element name="vST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
 *                                       &lt;element name="vProd" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface TNFe {


    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link ptc.SignatureType}
     *     {@link ptc.Signature}
     */
    ptc.SignatureType getSignature();

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ptc.SignatureType}
     *     {@link ptc.Signature}
     */
    void setSignature(ptc.SignatureType value);

    /**
     * Informações da Nota Fiscal Eletrônica
     * 
     * @return
     *     possible object is
     *     {@link ptc.TNFe.InfNFeType}
     */
    ptc.TNFe.InfNFeType getInfNFe();

    /**
     * Informações da Nota Fiscal Eletrônica
     * 
     * @param value
     *     allowed object is
     *     {@link ptc.TNFe.InfNFeType}
     */
    void setInfNFe(ptc.TNFe.InfNFeType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 14)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ide">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cUF" type="{http://www.portalfiscal.inf.br/nfe}TCodUfIBGE"/>
     *                   &lt;element name="nNF" type="{http://www.portalfiscal.inf.br/nfe}TNF"/>
     *                   &lt;element name="dEmi" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="emit">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
     *                     &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
     *                   &lt;/choice>
     *                   &lt;element name="xNome">
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;maxLength value="60"/>
     *                       &lt;minLength value="1"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/element>
     *                   &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="dest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
     *                     &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
     *                   &lt;/choice>
     *                   &lt;element name="xNome">
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;maxLength value="60"/>
     *                       &lt;minLength value="1"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/element>
     *                   &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="total">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ICMSTot">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="vBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
     *                             &lt;element name="vICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
     *                             &lt;element name="vBCST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
     *                             &lt;element name="vST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
     *                             &lt;element name="vProd" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface InfNFeType {


        /**
         * identificação da NF-e
         * 
         * @return
         *     possible object is
         *     {@link ptc.TNFe.InfNFeType.IdeType}
         */
        ptc.TNFe.InfNFeType.IdeType getIde();

        /**
         * identificação da NF-e
         * 
         * @param value
         *     allowed object is
         *     {@link ptc.TNFe.InfNFeType.IdeType}
         */
        void setIde(ptc.TNFe.InfNFeType.IdeType value);

        /**
         * Identificação do Emitente
         * 
         * @return
         *     possible object is
         *     {@link ptc.TNFe.InfNFeType.EmitType}
         */
        ptc.TNFe.InfNFeType.EmitType getEmit();

        /**
         * Identificação do Emitente
         * 
         * @param value
         *     allowed object is
         *     {@link ptc.TNFe.InfNFeType.EmitType}
         */
        void setEmit(ptc.TNFe.InfNFeType.EmitType value);

        /**
         * Identificação do Destinatário ou Remetente
         * 
         * @return
         *     possible object is
         *     {@link ptc.TNFe.InfNFeType.DestType}
         */
        ptc.TNFe.InfNFeType.DestType getDest();

        /**
         * Identificação do Destinatário ou Remetente
         * 
         * @param value
         *     allowed object is
         *     {@link ptc.TNFe.InfNFeType.DestType}
         */
        void setDest(ptc.TNFe.InfNFeType.DestType value);

        /**
         * Dados dos totais da NF-e
         * 
         * @return
         *     possible object is
         *     {@link ptc.TNFe.InfNFeType.TotalType}
         */
        ptc.TNFe.InfNFeType.TotalType getTotal();

        /**
         * Dados dos totais da NF-e
         * 
         * @param value
         *     allowed object is
         *     {@link ptc.TNFe.InfNFeType.TotalType}
         */
        void setTotal(ptc.TNFe.InfNFeType.TotalType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 82)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
         *           &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
         *         &lt;/choice>
         *         &lt;element name="xNome">
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;maxLength value="60"/>
         *             &lt;minLength value="1"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/element>
         *         &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface DestType {


            /**
             * Número do CPF
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getCPF();

            /**
             * Número do CPF
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setCPF(java.lang.String value);

            /**
             * Sigla da Unidade da Federação
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getUF();

            /**
             * Sigla da Unidade da Federação
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setUF(java.lang.String value);

            /**
             * Razão­ Social ou nome do destinatário
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getXNome();

            /**
             * Razão­ Social ou nome do destinatário
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setXNome(java.lang.String value);

            /**
             * Número do CNPJ
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getCNPJ();

            /**
             * Número do CNPJ
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setCNPJ(java.lang.String value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 44)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/>
         *           &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/>
         *         &lt;/choice>
         *         &lt;element name="xNome">
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;maxLength value="60"/>
         *             &lt;minLength value="1"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/element>
         *         &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface EmitType {


            /**
             * Número do CPF
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getCPF();

            /**
             * Número do CPF
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setCPF(java.lang.String value);

            /**
             * Sigla da Unidade da Federação
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getUF();

            /**
             * Sigla da Unidade da Federação
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setUF(java.lang.String value);

            /**
             * Razão Social ou Nome do emitente
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getXNome();

            /**
             * Razão Social ou Nome do emitente
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setXNome(java.lang.String value);

            /**
             * Número do CNPJ
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getCNPJ();

            /**
             * Número do CNPJ
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setCNPJ(java.lang.String value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 20)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cUF" type="{http://www.portalfiscal.inf.br/nfe}TCodUfIBGE"/>
         *         &lt;element name="nNF" type="{http://www.portalfiscal.inf.br/nfe}TNF"/>
         *         &lt;element name="dEmi" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface IdeType {


            /**
             * Data de emissão­ do Documento Fiscal (AAAA-MM-DD)
             * 
             * @return
             *     possible object is
             *     {@link java.util.Calendar}
             */
            java.util.Calendar getDEmi();

            /**
             * Data de emissão­ do Documento Fiscal (AAAA-MM-DD)
             * 
             * @param value
             *     allowed object is
             *     {@link java.util.Calendar}
             */
            void setDEmi(java.util.Calendar value);

            /**
             * Código da UF do emitente do Documento Fiscal. Utilizar a Tabela do IBGE.
             * 
             */
            short getCUF();

            /**
             * Código da UF do emitente do Documento Fiscal. Utilizar a Tabela do IBGE.
             * 
             */
            void setCUF(short value);

            /**
             * Número do Documento Fiscal
             * 
             * @return
             *     possible object is
             *     {@link java.math.BigInteger}
             */
            java.math.BigInteger getNNF();

            /**
             * Número do Documento Fiscal
             * 
             * @param value
             *     allowed object is
             *     {@link java.math.BigInteger}
             */
            void setNNF(java.math.BigInteger value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 120)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ICMSTot">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="vBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
         *                   &lt;element name="vICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
         *                   &lt;element name="vBCST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
         *                   &lt;element name="vST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
         *                   &lt;element name="vProd" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface TotalType {


            /**
             * Totais referentes ao ICMS
             * 
             * @return
             *     possible object is
             *     {@link ptc.TNFe.InfNFeType.TotalType.ICMSTotType}
             */
            ptc.TNFe.InfNFeType.TotalType.ICMSTotType getICMSTot();

            /**
             * Totais referentes ao ICMS
             * 
             * @param value
             *     allowed object is
             *     {@link ptc.TNFe.InfNFeType.TotalType.ICMSTotType}
             */
            void setICMSTot(ptc.TNFe.InfNFeType.TotalType.ICMSTotType value);


            /**
             * Java content class for anonymous complex type.
             * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/dadosNFsPTC.xsd line 126)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="vBC" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
             *         &lt;element name="vICMS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
             *         &lt;element name="vBCST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
             *         &lt;element name="vST" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
             *         &lt;element name="vProd" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface ICMSTotType {


                /**
                 * Valor Total do ICMS
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.math.BigDecimal}
                 */
                java.math.BigDecimal getVICMS();

                /**
                 * Valor Total do ICMS
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.math.BigDecimal}
                 */
                void setVICMS(java.math.BigDecimal value);

                /**
                 * BC do ICMS ST
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.math.BigDecimal}
                 */
                java.math.BigDecimal getVBCST();

                /**
                 * BC do ICMS ST
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.math.BigDecimal}
                 */
                void setVBCST(java.math.BigDecimal value);

                /**
                 * Valor Total do ICMS ST
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.math.BigDecimal}
                 */
                java.math.BigDecimal getVST();

                /**
                 * Valor Total do ICMS ST
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.math.BigDecimal}
                 */
                void setVST(java.math.BigDecimal value);

                /**
                 * BC do ICMS
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.math.BigDecimal}
                 */
                java.math.BigDecimal getVBC();

                /**
                 * BC do ICMS
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.math.BigDecimal}
                 */
                void setVBC(java.math.BigDecimal value);

                /**
                 * Valor Total dos produtos e serviços
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.math.BigDecimal}
                 */
                java.math.BigDecimal getVProd();

                /**
                 * Valor Total dos produtos e serviços
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.math.BigDecimal}
                 */
                void setVProd(java.math.BigDecimal value);

            }

        }

    }

}
