//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.21 at 02:41:30 PM GMT-03:00 
//


package ptc;


/**
 * Tipo Dados do Veículo
 * Java content class for TVeiculo complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/c:/WebPhp5/web/Nfs/schemas/tiposNFe_v1.04.xsd line 866)
 * <p>
 * <pre>
 * &lt;complexType name="TVeiculo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="placa">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="8"/>
 *             &lt;pattern value="[A-Z0-9]+"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface TVeiculo {


    /**
     * Placa do veículo
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPlaca();

    /**
     * Placa do veículo
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPlaca(java.lang.String value);

    /**
     * Sigla da UF
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getUF();

    /**
     * Sigla da UF
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setUF(java.lang.String value);

}
